version: '3.7'
services:
  #PHP Service
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      target: development
    container_name: php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAG: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks: 
      - app-network
    depends_on:
      - db
  
  # Nginx service
  server:
    image: nginx:alpine
    container_name: server
    restart: unless-stopped
    tty: true
    ports:
      - "9000:80"
      - "9001:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:  
      - php

  # MYSQL Service
  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker/mysql/db/data:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
  
# Docker network
networks:
  app-network:
    driver: bridge

# volumes:
#   dbdata:
#     driver: local
